In [1]:
import os
import warnings


import pandas as pd
from dotenv import load_dotenv
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, log_loss
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier




import mlflow
import mlflow.xgboost
import mlflow.lightgbm
from mlflow.models import infer_signature

warnings.filterwarnings("ignore")
load_dotenv()

True

In [3]:
import xgboost as xgb

In [4]:
import lightgbm as lgb

In [6]:
# Для локального стенда из docker-compose
os.environ["AWS_ACCESS_KEY_ID"] = os.getenv("AWS_ACCESS_KEY_ID", "admin")
os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("AWS_SECRET_ACCESS_KEY", "password")
raw_s3_endpoint = os.getenv("MLFLOW_S3_ENDPOINT_URL", "http://localhost:9000")

# `minio` резолвится только внутри docker-сети. Для локального ноутбука нужен localhost.
if "minio:9000" in raw_s3_endpoint:
    raw_s3_endpoint = "http://localhost:9000"
os.environ["MLFLOW_S3_ENDPOINT_URL"] = raw_s3_endpoint

# Если на сервере включена basic-auth, задайте логин/пароль
# os.environ["MLFLOW_TRACKING_USERNAME"] = os.getenv("MLFLOW_TRACKING_USERNAME", "admin")
# os.environ["MLFLOW_TRACKING_PASSWORD"] = os.getenv("MLFLOW_TRACKING_PASSWORD", "password")

MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI", "http://localhost:5050")
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)

print("MLflow URI:", mlflow.get_tracking_uri())

MLflow URI: http://localhost:5050

In [19]:
# Быстрая проверка подключения
mlflow.search_experiments(max_results=3)

[<Experiment: artifact_location='mlflow-artifacts:/', creation_time=1779729473752, experiment_id='1', last_update_time=1779729473752, lifecycle_stage='active', name='decision_tree', tags={}, trace_location=None, workspace='default'>,
 <Experiment: artifact_location='s3://mlflow-bucket/mlflow/0', creation_time=1779728934723, experiment_id='0', last_update_time=1779728934723, lifecycle_stage='active', name='Default', tags={}, trace_location=None, workspace='default'>]

In [7]:
X = pd.read_csv('../formatted_data/X_final.csv')
y = pd.read_csv('../formatted_data/y_final.csv')
RANDOM_STATE = 42
target_cols_final = y.columns.tolist()

In [ ]:
from mlflow.tracking import MlflowClient

experiment_name = "decision_tree"
artifact_location = "mlflow-artifacts:/"
client = MlflowClient()

exp = mlflow.get_experiment_by_name(experiment_name)
if exp is None:
    exp_id = client.create_experiment(
        name=experiment_name,
        artifact_location=artifact_location
    )
    print("Created experiment:", exp_id)
else:
    exp_id = exp.experiment_id
    print("Using existing experiment:", exp_id, "artifact_location=", exp.artifact_location)

mlflow.set_experiment(experiment_name)

registered_model_name = "decision_tree_model"

params = {
    "max_depth": 20,
    "min_samples_split": 5,
    "random_state": RANDOM_STATE
}

results = {}

Created experiment: 1

In [ ]:
for cat in target_cols_final:

    print(f"\nTARGET: {cat}")

    mask = y[cat].notna()

    X_cat = X[mask]
    y_cat = y.loc[mask, cat]

    if len(y_cat) == 0:
        continue

    X_train, X_test, y_train, y_test = train_test_split(
        X_cat,
        y_cat,
        test_size=0.2,
        random_state=RANDOM_STATE
    )

    with mlflow.start_run(
        run_name=f"dtree_{cat}"
    ):

        model = DecisionTreeClassifier(**params)

        model.fit(X_train, y_train)

        proba = model.predict_proba(X_test)[:, 1]

        roc_auc = roc_auc_score(y_test, proba)

        mlflow.log_params(params)

        mlflow.log_param("target", cat)

        mlflow.log_metric("roc_auc", float(roc_auc))

        signature = infer_signature(X_test, proba)

        registered_model_name = f"decision_tree_{cat}"

        model_info = mlflow.sklearn.log_model(
            sk_model=model,
            artifact_path="model",
            signature=signature,
            input_example=X_test.head(5),
            registered_model_name=registered_model_name,
        )
        new_version = model_info.registered_model_version

        client.set_registered_model_alias(
            registered_model_name,
            "prd",
            new_version
        )

        print("PRD alias ->", new_version)

        mlflow.set_tag("model_type", "DecisionTreeClassifier")
        results[cat] = {
            "roc_auc": roc_auc,
            "run_id": mlflow.active_run().info.run_id,
            "model_version": model_info.registered_model_version
        }

        print("ROC-AUC:", roc_auc)
        print("Run ID:", mlflow.active_run().info.run_id)


results_df = pd.DataFrame.from_dict(results, orient="index")

print(results_df)

========== TARGET: acute_toxicity ==========

2026/05/25 20:34:02 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:34:02 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:34:05 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_acute_toxicity' already exists. Creating a new version of this model...
2026/05/25 20:34:05 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_acute_toxicity, version 2
Created version '2' of model 'decision_tree_acute_toxicity'.
2026/05/25 20:34:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

PRD alias -> 2
ROC-AUC: 0.6763550149469126
Run ID: 079a46d03e954ee8973c806c2876ce4b
🏃 View run dtree_acute_toxicity at: http://localhost:5050/#/experiments/1/runs/079a46d03e954ee8973c806c2876ce4b
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: carcinogenicity ==========

2026/05/25 20:34:06 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:34:08 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_carcinogenicity' already exists. Creating a new version of this model...
2026/05/25 20:34:08 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_carcinogenicity, version 2
Created version '2' of model 'decision_tree_carcinogenicity'.

PRD alias -> 2
ROC-AUC: 0.5851715686274509
Run ID: 9945d10047af4b1aa07fb12081dce45b
🏃 View run dtree_carcinogenicity at: http://localhost:5050/#/experiments/1/runs/9945d10047af4b1aa07fb12081dce45b
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: cardiotoxicity ==========

2026/05/25 20:34:27 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:34:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:34:30 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_cardiotoxicity' already exists. Creating a new version of this model...
2026/05/25 20:34:33 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_cardiotoxicity, version 2
Created version '2' of model 'decision_tree_cardiotoxicity'.

PRD alias -> 2
ROC-AUC: 0.6776766818930579
Run ID: 6727c31769c744a1a7ab103f24f1da92
🏃 View run dtree_cardiotoxicity at: http://localhost:5050/#/experiments/1/runs/6727c31769c744a1a7ab103f24f1da92
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: dermal_toxicity ==========

2026/05/25 20:34:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:34:34 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:34:36 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_dermal_toxicity' already exists. Creating a new version of this model...
2026/05/25 20:34:36 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_dermal_toxicity, version 2
Created version '2' of model 'decision_tree_dermal_toxicity'.

PRD alias -> 2
ROC-AUC: 0.6495556076836865
Run ID: 3f3f987ad68046d09a504a9246f9e44f
🏃 View run dtree_dermal_toxicity at: http://localhost:5050/#/experiments/1/runs/3f3f987ad68046d09a504a9246f9e44f
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: genotoxicity ==========

2026/05/25 20:34:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:34:37 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:34:39 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_genotoxicity' already exists. Creating a new version of this model...
2026/05/25 20:34:39 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_genotoxicity, version 2
Created version '2' of model 'decision_tree_genotoxicity'.

PRD alias -> 2
ROC-AUC: 0.7667095959438085
Run ID: 6a5a6859d5de45048046a8c3330cb15c
🏃 View run dtree_genotoxicity at: http://localhost:5050/#/experiments/1/runs/6a5a6859d5de45048046a8c3330cb15c
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: hepatotoxicity ==========

2026/05/25 20:34:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:34:40 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:34:44 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_hepatotoxicity' already exists. Creating a new version of this model...
2026/05/25 20:34:45 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_hepatotoxicity, version 2
Created version '2' of model 'decision_tree_hepatotoxicity'.

PRD alias -> 2
ROC-AUC: 0.6532890260617475
Run ID: e12595960975413097344619b27526a4
🏃 View run dtree_hepatotoxicity at: http://localhost:5050/#/experiments/1/runs/e12595960975413097344619b27526a4
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: ocular_toxicity ==========

2026/05/25 20:34:45 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:34:45 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:34:48 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_ocular_toxicity' already exists. Creating a new version of this model...
2026/05/25 20:34:48 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_ocular_toxicity, version 2
Created version '2' of model 'decision_tree_ocular_toxicity'.

PRD alias -> 2
ROC-AUC: 0.7509028809028808
Run ID: 0982bf3d097343dc9d90bbcde59131fe
🏃 View run dtree_ocular_toxicity at: http://localhost:5050/#/experiments/1/runs/0982bf3d097343dc9d90bbcde59131fe
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: oxidative_stress ==========

2026/05/25 20:34:49 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:34:49 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:34:51 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_oxidative_stress' already exists. Creating a new version of this model...
2026/05/25 20:34:51 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_oxidative_stress, version 2
Created version '2' of model 'decision_tree_oxidative_stress'.
2026/05/25 20:34:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:34:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

PRD alias -> 2
ROC-AUC: 0.5951397628735393
Run ID: 3fbdacf03d394176b34c6883f2240925
🏃 View run dtree_oxidative_stress at: http://localhost:5050/#/experiments/1/runs/3fbdacf03d394176b34c6883f2240925
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: respiratory_toxicity ==========

2026/05/25 20:34:53 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_respiratory_toxicity' already exists. Creating a new version of this model...
2026/05/25 20:34:53 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_respiratory_toxicity, version 2
Created version '2' of model 'decision_tree_respiratory_toxicity'.
2026/05/25 20:34:54 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

PRD alias -> 2
ROC-AUC: 0.6734144927536232
Run ID: 216efde5d7a144069b3db648ab214533
🏃 View run dtree_respiratory_toxicity at: http://localhost:5050/#/experiments/1/runs/216efde5d7a144069b3db648ab214533
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: neuro_sensory_toxicity ==========

2026/05/25 20:34:54 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:34:55 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_neuro_sensory_toxicity' already exists. Creating a new version of this model...
2026/05/25 20:34:56 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_neuro_sensory_toxicity, version 2
Created version '2' of model 'decision_tree_neuro_sensory_toxicity'.

PRD alias -> 2
ROC-AUC: 0.6694190424959656
Run ID: c6ce9d40c3ba49c2a2a6f9c8f3a00d32
🏃 View run dtree_neuro_sensory_toxicity at: http://localhost:5050/#/experiments/1/runs/c6ce9d40c3ba49c2a2a6f9c8f3a00d32
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: immuno_hematotoxicity ==========

2026/05/25 20:34:56 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:34:56 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:34:58 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_immuno_hematotoxicity' already exists. Creating a new version of this model...
2026/05/25 20:34:58 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_immuno_hematotoxicity, version 2
Created version '2' of model 'decision_tree_immuno_hematotoxicity'.
2026/05/25 20:34:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:34:58 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

PRD alias -> 2
ROC-AUC: 0.6702242733851929
Run ID: cf77fad09295497ebdeb93953462f076
🏃 View run dtree_immuno_hematotoxicity at: http://localhost:5050/#/experiments/1/runs/cf77fad09295497ebdeb93953462f076
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: reprod_dev_toxicity ==========

2026/05/25 20:35:00 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_reprod_dev_toxicity' already exists. Creating a new version of this model...
2026/05/25 20:35:00 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_reprod_dev_toxicity, version 2
Created version '2' of model 'decision_tree_reprod_dev_toxicity'.

PRD alias -> 2
ROC-AUC: 0.46534653465346537
Run ID: 0990e9e8a78445b8ac617caff6432caa
🏃 View run dtree_reprod_dev_toxicity at: http://localhost:5050/#/experiments/1/runs/0990e9e8a78445b8ac617caff6432caa
🧪 View experiment at: http://localhost:5050/#/experiments/1

========== TARGET: endocrine_metabolic_tox ==========

2026/05/25 20:35:01 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/25 20:35:01 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/25 20:35:02 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'decision_tree_endocrine_metabolic_tox' already exists. Creating a new version of this model...
2026/05/25 20:35:03 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: decision_tree_endocrine_metabolic_tox, version 2
Created version '2' of model 'decision_tree_endocrine_metabolic_tox'.

PRD alias -> 2
ROC-AUC: 0.6397356122663306
Run ID: 2f8ac3e61ad24c66912fc6c8493baa44
🏃 View run dtree_endocrine_metabolic_tox at: http://localhost:5050/#/experiments/1/runs/2f8ac3e61ad24c66912fc6c8493baa44
🧪 View experiment at: http://localhost:5050/#/experiments/1
                          roc_auc                            run_id  \
acute_toxicity           0.676355  079a46d03e954ee8973c806c2876ce4b
carcinogenicity          0.585172  9945d10047af4b1aa07fb12081dce45b
cardiotoxicity           0.677677  6727c31769c744a1a7ab103f24f1da92
dermal_toxicity          0.649556  3f3f987ad68046d09a504a9246f9e44f
genotoxicity             0.766710  6a5a6859d5de45048046a8c3330cb15c
hepatotoxicity           0.653289  e12595960975413097344619b27526a4
ocular_toxicity          0.750903  0982bf3d097343dc9d90bbcde59131fe
oxidative_stress         0.595140  3fbdacf03d394176b34c6883f2240925
respiratory_toxicity     0.673414  216efde5d7a144069b3db648ab214533
neuro_sensory_toxicity   0.669419  c6ce9d40c3ba49c2a2a6f9c8f3a00d32
immuno_hematotoxicity    0.670224  cf77fad09295497ebdeb93953462f076
reprod_dev_toxicity      0.465347  0990e9e8a78445b8ac617caff6432caa
endocrine_metabolic_tox  0.639736  2f8ac3e61ad24c66912fc6c8493baa44

                        model_version
acute_toxicity                      2
carcinogenicity                     2
cardiotoxicity                      2
dermal_toxicity                     2
genotoxicity                        2
hepatotoxicity                      2
ocular_toxicity                     2
oxidative_stress                    2
respiratory_toxicity                2
neuro_sensory_toxicity              2
immuno_hematotoxicity               2
reprod_dev_toxicity                 2
endocrine_metabolic_tox             2

In [12]:
runs_df = mlflow.search_runs(
    experiment_names=[experiment_name],
    order_by=["metrics.roc_auc DESC"],
)
runs_df[["run_id","metrics.roc_auc", "artifact_uri"]].head()

,run_id,metrics.roc_auc,artifact_uri
0,6a5a6859d5de45048046a8c3330cb15c,0.766710,mlflow-artifacts:/6a5a6859d5de45048046a8c3330c...
1,d218e45b31db4df3be74ce7eabe21c0a,0.766710,mlflow-artifacts:/d218e45b31db4df3be74ce7eabe2...
2,0982bf3d097343dc9d90bbcde59131fe,0.750903,mlflow-artifacts:/0982bf3d097343dc9d90bbcde591...
3,9fdf0b918f1b4a848ca61a5f2efd2ac0,0.750903,mlflow-artifacts:/9fdf0b918f1b4a848ca61a5f2efd...
4,6727c31769c744a1a7ab103f24f1da92,0.677677,mlflow-artifacts:/6727c31769c744a1a7ab103f24f1...

In [13]:
mlflow.search_runs(experiment_names=[experiment_name])

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.roc_auc,params.max_depth,params.min_samples_split,params.random_state,params.target,tags.mlflow.user,tags.mlflow.source.type,tags.mlflow.runName,tags.mlflow.source.name,tags.model_type
0,2f8ac3e61ad24c66912fc6c8493baa44,1,FINISHED,mlflow-artifacts:/2f8ac3e61ad24c66912fc6c8493b...,2026-05-25 17:35:00.829000+00:00,2026-05-25 17:35:03.214000+00:00,0.639736,20,5,42,endocrine_metabolic_tox,kuzmndmtry,NOTEBOOK,dtree_endocrine_metabolic_tox,ML_flow.ipynb,DecisionTreeClassifier
1,0990e9e8a78445b8ac617caff6432caa,1,FINISHED,mlflow-artifacts:/0990e9e8a78445b8ac617caff643...,2026-05-25 17:34:58.639000+00:00,2026-05-25 17:35:00.788000+00:00,0.465347,20,5,42,reprod_dev_toxicity,kuzmndmtry,NOTEBOOK,dtree_reprod_dev_toxicity,ML_flow.ipynb,DecisionTreeClassifier
2,cf77fad09295497ebdeb93953462f076,1,FINISHED,mlflow-artifacts:/cf77fad09295497ebdeb93953462...,2026-05-25 17:34:56.206000+00:00,2026-05-25 17:34:58.566000+00:00,0.670224,20,5,42,immuno_hematotoxicity,kuzmndmtry,NOTEBOOK,dtree_immuno_hematotoxicity,ML_flow.ipynb,DecisionTreeClassifier
3,c6ce9d40c3ba49c2a2a6f9c8f3a00d32,1,FINISHED,mlflow-artifacts:/c6ce9d40c3ba49c2a2a6f9c8f3a0...,2026-05-25 17:34:54.097000+00:00,2026-05-25 17:34:56.178000+00:00,0.669419,20,5,42,neuro_sensory_toxicity,kuzmndmtry,NOTEBOOK,dtree_neuro_sensory_toxicity,ML_flow.ipynb,DecisionTreeClassifier
4,216efde5d7a144069b3db648ab214533,1,FINISHED,mlflow-artifacts:/216efde5d7a144069b3db648ab21...,2026-05-25 17:34:51.806000+00:00,2026-05-25 17:34:54.012000+00:00,0.673414,20,5,42,respiratory_toxicity,kuzmndmtry,NOTEBOOK,dtree_respiratory_toxicity,ML_flow.ipynb,DecisionTreeClassifier
5,3fbdacf03d394176b34c6883f2240925,1,FINISHED,mlflow-artifacts:/3fbdacf03d394176b34c6883f224...,2026-05-25 17:34:49.060000+00:00,2026-05-25 17:34:51.784000+00:00,0.595140,20,5,42,oxidative_stress,kuzmndmtry,NOTEBOOK,dtree_oxidative_stress,ML_flow.ipynb,DecisionTreeClassifier
6,0982bf3d097343dc9d90bbcde59131fe,1,FINISHED,mlflow-artifacts:/0982bf3d097343dc9d90bbcde591...,2026-05-25 17:34:45.361000+00:00,2026-05-25 17:34:48.973000+00:00,0.750903,20,5,42,ocular_toxicity,kuzmndmtry,NOTEBOOK,dtree_ocular_toxicity,ML_flow.ipynb,DecisionTreeClassifier
7,e12595960975413097344619b27526a4,1,FINISHED,mlflow-artifacts:/e12595960975413097344619b275...,2026-05-25 17:34:39.858000+00:00,2026-05-25 17:34:45.224000+00:00,0.653289,20,5,42,hepatotoxicity,kuzmndmtry,NOTEBOOK,dtree_hepatotoxicity,ML_flow.ipynb,DecisionTreeClassifier
8,6a5a6859d5de45048046a8c3330cb15c,1,FINISHED,mlflow-artifacts:/6a5a6859d5de45048046a8c3330c...,2026-05-25 17:34:37.006000+00:00,2026-05-25 17:34:39.759000+00:00,0.766710,20,5,42,genotoxicity,kuzmndmtry,NOTEBOOK,dtree_genotoxicity,ML_flow.ipynb,DecisionTreeClassifier
9,3f3f987ad68046d09a504a9246f9e44f,1,FINISHED,mlflow-artifacts:/3f3f987ad68046d09a504a9246f9...,2026-05-25 17:34:34.245000+00:00,2026-05-25 17:34:36.869000+00:00,0.649556,20,5,42,dermal_toxicity,kuzmndmtry,NOTEBOOK,dtree_dermal_toxicity,ML_flow.ipynb,DecisionTreeClassifier
10,6727c31769c744a1a7ab103f24f1da92,1,FINISHED,mlflow-artifacts:/6727c31769c744a1a7ab103f24f1...,2026-05-25 17:34:08.798000+00:00,2026-05-25 17:34:34.011000+00:00,0.677677,20,5,42,cardiotoxicity,kuzmndmtry,NOTEBOOK,dtree_cardiotoxicity,ML_flow.ipynb,DecisionTreeClassifier
11,9945d10047af4b1aa07fb12081dce45b,1,FINISHED,mlflow-artifacts:/9945d10047af4b1aa07fb12081dc...,2026-05-25 17:34:06.113000+00:00,2026-05-25 17:34:08.394000+00:00,0.585172,20,5,42,carcinogenicity,kuzmndmtry,NOTEBOOK,dtree_carcinogenicity,ML_flow.ipynb,DecisionTreeClassifier
12,079a46d03e954ee8973c806c2876ce4b,1,FINISHED,mlflow-artifacts:/079a46d03e954ee8973c806c2876...,2026-05-25 17:34:01.654000+00:00,2026-05-25 17:34:06.033000+00:00,0.676355,20,5,42,acute_toxicity,kuzmndmtry,NOTEBOOK,dtree_acute_toxicity,ML_flow.ipynb,DecisionTreeClassifier
13,ab00d0aa0904436395742518a0b42944,1,FINISHED,mlflow-artifacts:/ab00d0aa0904436395742518a0b4...,2026-05-25 17:18:56.448000+00:00,2026-05-25 17:18:59.911000+00:00,0.639736,20,5,42,endocrine_metabolic_tox,kuzmndmtry,NOTEBOOK,dtree_endocrine_metabolic_tox,ML_flow.ipynb,DecisionTreeClassifier
14,405d399b5a9d4026809b8d45b03f24e9,1,FINISHED,mlflow-artifacts:/405d399b5a9d4026809b8d45b03f...,2026-05-25 17:18:53.112000+00:00,2026-05-25 17:18:56.307000+00:00,0.465347,20,5,42,reprod_dev_toxicity,kuzmndmtry,NOTEBOOK,dtree_reprod_dev_toxicity,ML_flow.ipynb,DecisionTreeClassifier
15,d589d0ab43e64307983ac32c5d428f5f,1,FINISHED,mlflow-artifacts:/d589d0ab43e64307983ac32c5d42...,2026-05-25 17:18:50.216000+00:00,2026-05-25 17:18:53.023000+00:00,0.670224,20,5,42,immuno_hematotoxicity,kuzmndmtry,NOTEBOOK,dtree_immuno_hematotoxicity,ML_flow.ipynb,DecisionTreeClassifier
16,39e1b28fc2ea4956b2bbc20a7eb6e7ba,1,FINISHED,mlflow-artifacts:/39e1b28fc2ea4956b2bbc20a7eb6...,2026-05-25 17:18:47.531000+00:00,2026-05-25 17:18:50.125000+00:00,0.669419,20,5,42,neuro_sensory_toxicity,kuzmndmtry,NOTEBOOK,dtree_neuro_sensory_toxicity,ML_flow.ipynb,DecisionTreeClassifier
17,1b98d378030a40c7b5a7d4b9cfabc0d9,1,FINISHED,mlflow-artifacts:/1b98d378030a40c7b5a7d4b9cfab...,2026-05-25 17:18:45.423000+00:00,2026-05-25 17:18:47.512000+00:00,0.673414,20,5,42,respiratory_toxicity,kuzmndmtry,NOTEBOOK,dtree_respiratory_toxicity,ML_flow.ipynb,DecisionTreeClassifier
18,0a91c7d656f44d65b2e362fe61a68b95,1,FINISHED,mlflow-artifacts:/0a91c7d656f44d65b2e362fe61a6...,2026-05-25 17:18:42.955000+00:00,2026-05-25 17:18:45.318000+00:00,0.595140,20,5,42,oxidative_stress,kuzmndmtry,NOTEBOOK,dtree_oxidative_stress,ML_flow.ipynb,DecisionTreeClassifier
19,9fdf0b918f1b4a848ca61a5f2efd2ac0,1,FINISHED,mlflow-artifacts:/9fdf0b918f1b4a848ca61a5f2efd...,2026-05-25 17:18:40.676000+00:00,2026-05-25 17:18:42.914000+00:00,0.750903,20,5,42,ocular_toxicity,kuzmndmtry,NOTEBOOK,dtree_ocular_toxicity,ML_flow.ipynb,DecisionTreeClassifier
20,ecd412c2add541cdae3b037b75c87755,1,FINISHED,mlflow-artifacts:/ecd412c2add541cdae3b037b75c8...,2026-05-25 17:18:38.160000+00:00,2026-05-25 17:18:40.639000+00:00,0.653289,20,5,42,hepatotoxicity,kuzmndmtry,NOTEBOOK,dtree_hepatotoxicity,ML_flow.ipynb,DecisionTreeClassifier
21,d218e45b31db4df3be74ce7eabe21c0a,1,FINISHED,mlflow-artifacts:/d218e45b31db4df3be74ce7eabe2...,2026-05-25 17:18:35.044000+00:00,2026-05-25 17:18:38.075000+00:00,0.766710,20,5,42,genotoxicity,kuzmndmtry,NOTEBOOK,dtree_genotoxicity,ML_flow.ipynb,DecisionTreeClassifier
22,10ffe3e77125430989f79e91d05b7f1b,1,FINISHED,mlflow-artifacts:/10ffe3e77125430989f79e91d05b...,2026-05-25 17:18:31.862000+00:00,2026-05-25 17:18:34.936000+00:00,0.649556,20,5,42,dermal_toxicity,kuzmndmtry,NOTEBOOK,dtree_dermal_toxicity,ML_flow.ipynb,DecisionTreeClassifier
23,bedca5c56d5f4c53abacd89b3b4fac75,1,FINISHED,mlflow-artifacts:/bedca5c56d5f4c53abacd89b3b4f...,2026-05-25 17:18:10.207000+00:00,2026-05-25 17:18:31.711000+00:00,0.677677,20,5,42,cardiotoxicity,kuzmndmtry,NOTEBOOK,dtree_cardiotoxicity,ML_flow.ipynb,DecisionTreeClassifier
24,13d7cb6fdffe43b6867929bc30127ee3,1,FINISHED,mlflow-artifacts:/13d7cb6fdffe43b6867929bc3012...,2026-05-25 17:18:07.038000+00:00,2026-05-25 17:18:09.955000+00:00,0.585172,20,5,42,carcinogenicity,kuzmndmtry,NOTEBOOK,dtree_carcinogenicity,ML_flow.ipynb,DecisionTreeClassifier
25,06841607d0314c1e8cf5b6c6dbb2e3df,1,FINISHED,mlflow-artifacts:/06841607d0314c1e8cf5b6c6dbb2...,2026-05-25 17:18:00.665000+00:00,2026-05-25 17:18:06.939000+00:00,0.676355,20,5,42,acute_toxicity,kuzmndmtry,NOTEBOOK,dtree_acute_toxicity,ML_flow.ipynb,DecisionTreeClassifier

In [14]:
loaded_model = mlflow.pyfunc.load_model(f"models:/{registered_model_name}@prd")

sample_pred = loaded_model.predict(X_test.head(3))
sample_pred

array([0., 0., 0.])

Random Forest

In [21]:
from mlflow.tracking import MlflowClient

experiment_name = "random_forest"
artifact_location = "mlflow-artifacts:/"
client = MlflowClient()

exp = mlflow.get_experiment_by_name(experiment_name)
if exp is None:
    exp_id = client.create_experiment(
        name=experiment_name,
        artifact_location=artifact_location
    )
    print("Created experiment:", exp_id)
else:
    exp_id = exp.experiment_id
    print("Using existing experiment:", exp_id, "artifact_location=", exp.artifact_location)

mlflow.set_experiment(experiment_name)

registered_model_name = "random_forest_model"

rf_param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "criterion": ["gini"],
    "max_features": ["sqrt"]
}

results = []

Created experiment: 2

In [23]:
for cat in target_cols_final:
    print(f"\nTARGET: {cat}")

    mask = y[cat].notna()

    X_cat = X[mask]
    y_cat = y.loc[mask, cat]

    if len(y_cat) == 0:
        continue

    X_train, X_test, y_train, y_test = train_test_split(
        X_cat,
        y_cat,
        test_size=0.2,
        random_state=RANDOM_STATE
    )

    with mlflow.start_run(run_name=f"rf_{cat}"):
        rf = RandomForestClassifier(
            random_state=42,
            n_jobs=-1
            )

        grid_search = GridSearchCV(

            estimator=rf,

            param_grid=rf_param_grid,

            cv=3,

            scoring="roc_auc",

            n_jobs=-1

        )

        grid_search.fit(X_train, y_train)

        best_model = grid_search.best_estimator_

        proba = best_model.predict_proba(X_test)[:, 1]

        roc_auc = roc_auc_score(y_test, proba)


        best_params = grid_search.best_params_

        metrics = {

            "roc_auc_test": float(roc_auc),

            "best_cv_score": float(grid_search.best_score_)

        }

        mlflow.log_params(best_params)

        mlflow.log_param("target", cat)

        mlflow.log_metrics(metrics)

        mlflow.set_tags({

            "model_type": "RandomForestClassifier",

            "target": cat

        })


        signature = infer_signature(X_test, proba)

        registered_model_name = f"random_forest_{cat}"

        model_info = mlflow.sklearn.log_model(

            sk_model=best_model,

            name="model",

            signature=signature,

            input_example=X_test.head(5),

            registered_model_name=registered_model_name,

        )

        new_version = model_info.registered_model_version

        client.set_registered_model_alias(

            registered_model_name,

            "prd",

            new_version

        )

        # feature importance artifact

        importance_df = pd.DataFrame({

            "feature": X_train.columns,

            "importance": best_model.feature_importances_

        }).sort_values("importance", ascending=False)

        importance_path = f"feature_importance_{cat}.csv"

        importance_df.to_csv(

            importance_path,

            index=False

        )

        mlflow.log_artifact(importance_path)



        results.append({

            "category": cat,

            "roc_auc_test": roc_auc,

            "best_cv_score": grid_search.best_score_,

            "best_params": best_params,

            "run_id": mlflow.active_run().info.run_id,

            "model_version": new_version

        })

        print("ROC-AUC TEST:", roc_auc)

        print("Best CV Score:", grid_search.best_score_)

        print("Best Params:", best_params)



results_rf = pd.DataFrame(results)

print(results_rf)

TARGET: acute_toxicity

2026/05/27 14:40:05 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:40:07 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_acute_toxicity'.
2026/05/27 14:40:09 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_acute_toxicity, version 1
Created version '1' of model 'random_forest_acute_toxicity'.

ROC-AUC TEST: 0.8409648489846407
Best CV Score: 0.8230414435494757
Best Params: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 100}
🏃 View run rf_acute_toxicity at: http://localhost:5050/#/experiments/2/runs/e2823d1363df44cf880f0aba558ae31e
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: carcinogenicity

2026/05/27 14:40:13 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:40:16 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_carcinogenicity'.
2026/05/27 14:40:16 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_carcinogenicity, version 1
Created version '1' of model 'random_forest_carcinogenicity'.

ROC-AUC TEST: 0.7314600840336134
Best CV Score: 0.7258832284353023
Best Params: {'criterion': 'gini', 'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}
🏃 View run rf_carcinogenicity at: http://localhost:5050/#/experiments/2/runs/6d376d64bce044a2b3bedf2e6a3d2bce
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: cardiotoxicity

2026/05/27 14:56:13 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:56:17 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_cardiotoxicity'.
2026/05/27 14:56:23 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_cardiotoxicity, version 1
Created version '1' of model 'random_forest_cardiotoxicity'.

ROC-AUC TEST: 0.9035046722111563
Best CV Score: 0.8954377300930655
Best Params: {'criterion': 'gini', 'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 200}
🏃 View run rf_cardiotoxicity at: http://localhost:5050/#/experiments/2/runs/117c5197e3dc4431b7e306d73e7d3edd
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: dermal_toxicity

2026/05/27 14:56:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:56:34 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_dermal_toxicity'.
2026/05/27 14:56:37 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_dermal_toxicity, version 1
Created version '1' of model 'random_forest_dermal_toxicity'.

ROC-AUC TEST: 0.8012615007688899
Best CV Score: 0.813160136764674
Best Params: {'criterion': 'gini', 'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}
🏃 View run rf_dermal_toxicity at: http://localhost:5050/#/experiments/2/runs/d75248d931244fe894ac0981962cdb04
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: genotoxicity

2026/05/27 14:57:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:57:08 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_genotoxicity'.
2026/05/27 14:57:11 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_genotoxicity, version 1
Created version '1' of model 'random_forest_genotoxicity'.

ROC-AUC TEST: 0.9115893418691741
Best CV Score: 0.9033422489620885
Best Params: {'criterion': 'gini', 'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}
🏃 View run rf_genotoxicity at: http://localhost:5050/#/experiments/2/runs/02e1275bab08408eb5b031ec11d1f9d6
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: hepatotoxicity

2026/05/27 14:57:21 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:57:25 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_hepatotoxicity'.
2026/05/27 14:57:26 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_hepatotoxicity, version 1
Created version '1' of model 'random_forest_hepatotoxicity'.

ROC-AUC TEST: 0.8360269393470264
Best CV Score: 0.8030800112291067
Best Params: {'criterion': 'gini', 'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
🏃 View run rf_hepatotoxicity at: http://localhost:5050/#/experiments/2/runs/5f71e93030974dcd8f386c83d6670959
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: ocular_toxicity

2026/05/27 14:57:37 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:57:41 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_ocular_toxicity'.
2026/05/27 14:57:42 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_ocular_toxicity, version 1
Created version '1' of model 'random_forest_ocular_toxicity'.

ROC-AUC TEST: 0.8960795960795961
Best CV Score: 0.9092203706556404
Best Params: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}
🏃 View run rf_ocular_toxicity at: http://localhost:5050/#/experiments/2/runs/bc803048ec654c28b8f82d08d71e775b
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: oxidative_stress

2026/05/27 14:57:56 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:57:59 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_oxidative_stress'.
2026/05/27 14:58:00 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_oxidative_stress, version 1
Created version '1' of model 'random_forest_oxidative_stress'.

ROC-AUC TEST: 0.805325773960077
Best CV Score: 0.8016761933463034
Best Params: {'criterion': 'gini', 'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}
🏃 View run rf_oxidative_stress at: http://localhost:5050/#/experiments/2/runs/bbaa42f17cac4fe1bd6921e5fd9ec0fe
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: respiratory_toxicity

2026/05/27 14:58:06 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:58:09 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_respiratory_toxicity'.
2026/05/27 14:58:10 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_respiratory_toxicity, version 1
Created version '1' of model 'random_forest_respiratory_toxicity'.

ROC-AUC TEST: 0.8829217391304348
Best CV Score: 0.829528173119977
Best Params: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 100}
🏃 View run rf_respiratory_toxicity at: http://localhost:5050/#/experiments/2/runs/4a27902b49844b3b842d27b2372927b3
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: neuro_sensory_toxicity

2026/05/27 14:58:15 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:58:18 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_neuro_sensory_toxicity'.
2026/05/27 14:58:18 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_neuro_sensory_toxicity, version 1
Created version '1' of model 'random_forest_neuro_sensory_toxicity'.

ROC-AUC TEST: 0.8556750941366326
Best CV Score: 0.8452815260613072
Best Params: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
🏃 View run rf_neuro_sensory_toxicity at: http://localhost:5050/#/experiments/2/runs/868b1eb7fef649cb82470adbfe4c97a4
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: immuno_hematotoxicity

/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Users/kuzmndmtry/ml/hse/yp/27_toxicity_prediction/.venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

ROC-AUC TEST: 0.8145845427454623
Best CV Score: 0.7890370803782852
Best Params: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 200}
🏃 View run rf_immuno_hematotoxicity at: http://localhost:5050/#/experiments/2/runs/04061456509a4d5a8eb59dca70135011
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: reprod_dev_toxicity

2026/05/27 14:58:46 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:58:49 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_reprod_dev_toxicity'.
2026/05/27 14:58:49 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_reprod_dev_toxicity, version 1
Created version '1' of model 'random_forest_reprod_dev_toxicity'.

ROC-AUC TEST: 0.8816831683168317
Best CV Score: 0.7740697619374091
Best Params: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 200}
🏃 View run rf_reprod_dev_toxicity at: http://localhost:5050/#/experiments/2/runs/563be08be3604bee88eacdc88cfec3ca
🧪 View experiment at: http://localhost:5050/#/experiments/2

TARGET: endocrine_metabolic_tox

2026/05/27 14:59:07 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/27 14:59:10 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'random_forest_endocrine_metabolic_tox'.
2026/05/27 14:59:11 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: random_forest_endocrine_metabolic_tox, version 1
Created version '1' of model 'random_forest_endocrine_metabolic_tox'.

ROC-AUC TEST: 0.7725774147087947
Best CV Score: 0.7585320103871132
Best Params: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}
🏃 View run rf_endocrine_metabolic_tox at: http://localhost:5050/#/experiments/2/runs/95653f266e3c48e48ffde3e3c5fce46b
🧪 View experiment at: http://localhost:5050/#/experiments/2
                   category  roc_auc_test  best_cv_score  \
0            acute_toxicity      0.840965       0.823041
1           carcinogenicity      0.731460       0.725883
2            cardiotoxicity      0.903505       0.895438
3           dermal_toxicity      0.801262       0.813160
4              genotoxicity      0.911589       0.903342
5            hepatotoxicity      0.836027       0.803080
6           ocular_toxicity      0.896080       0.909220
7          oxidative_stress      0.805326       0.801676
8      respiratory_toxicity      0.882922       0.829528
9    neuro_sensory_toxicity      0.855675       0.845282
10    immuno_hematotoxicity      0.814585       0.789037
11      reprod_dev_toxicity      0.881683       0.774070
12  endocrine_metabolic_tox      0.772577       0.758532

                                          best_params  \
0   {'criterion': 'gini', 'max_depth': 10, 'max_fe...
1   {'criterion': 'gini', 'max_depth': 20, 'max_fe...
2   {'criterion': 'gini', 'max_depth': 20, 'max_fe...
3   {'criterion': 'gini', 'max_depth': 20, 'max_fe...
4   {'criterion': 'gini', 'max_depth': 20, 'max_fe...
5   {'criterion': 'gini', 'max_depth': 20, 'max_fe...
6   {'criterion': 'gini', 'max_depth': 10, 'max_fe...
7   {'criterion': 'gini', 'max_depth': 20, 'max_fe...
8   {'criterion': 'gini', 'max_depth': 10, 'max_fe...
9   {'criterion': 'gini', 'max_depth': 10, 'max_fe...
10  {'criterion': 'gini', 'max_depth': 10, 'max_fe...
11  {'criterion': 'gini', 'max_depth': 10, 'max_fe...
12  {'criterion': 'gini', 'max_depth': 10, 'max_fe...

                              run_id model_version
0   e2823d1363df44cf880f0aba558ae31e             1
1   6d376d64bce044a2b3bedf2e6a3d2bce             1
2   117c5197e3dc4431b7e306d73e7d3edd             1
3   d75248d931244fe894ac0981962cdb04             1
4   02e1275bab08408eb5b031ec11d1f9d6             1
5   5f71e93030974dcd8f386c83d6670959             1
6   bc803048ec654c28b8f82d08d71e775b             1
7   bbaa42f17cac4fe1bd6921e5fd9ec0fe             1
8   4a27902b49844b3b842d27b2372927b3             1
9   868b1eb7fef649cb82470adbfe4c97a4             1
10  04061456509a4d5a8eb59dca70135011             1
11  563be08be3604bee88eacdc88cfec3ca             1
12  95653f266e3c48e48ffde3e3c5fce46b             1

Бустинги

In [8]:
from mlflow.tracking import MlflowClient

experiment_name = "lightGBM"
artifact_location = "mlflow-artifacts:/"
client = MlflowClient()

exp = mlflow.get_experiment_by_name(experiment_name)
if exp is None:
    exp_id = client.create_experiment(
        name=experiment_name,
        artifact_location=artifact_location
    )
    print("Created experiment:", exp_id)
else:
    exp_id = exp.experiment_id
    print("Using existing experiment:", exp_id, "artifact_location=", exp.artifact_location)

mlflow.set_experiment(experiment_name)

registered_model_name = "lightGBM_model"

lgb_param_grid = {
    "num_leaves": [31, 63],
    "learning_rate": [0.05, 0.1],
    "n_estimators": [200, 400],
    "subsample": [0.8, 1.0]
}

results = []

Using existing experiment: 3 artifact_location= mlflow-artifacts:/

In [10]:
for cat in y.columns.tolist():

    print(f"\nTARGET: {cat}")

    mask = y[cat].notna()

    X_cat = X[mask]
    y_cat = y.loc[mask, cat]

    if len(y_cat) == 0:
        continue

    X_train, X_test, y_train, y_test = train_test_split(
        X_cat,
        y_cat,
        test_size=0.2,
        random_state=42,
        stratify=y_cat
    )

    with mlflow.start_run(run_name=f"lgbm_{cat}"):

        lgb_model = lgb.LGBMClassifier(
            random_state=42,
            n_jobs=-1,
            device="cpu"
        )

        lgb_grid = GridSearchCV(
            estimator=lgb_model,
            param_grid=lgb_param_grid,
            cv=3,
            scoring="roc_auc",
            n_jobs=-1,
            verbose=2
        )

        lgb_grid.fit(X_train, y_train)

        lgb_best = lgb_grid.best_estimator_

        proba = lgb_best.predict_proba(X_test)[:, 1]

        roc_auc = roc_auc_score(y_test, proba)

        best_params = lgb_grid.best_params_

        metrics = {
            "roc_auc_test": float(roc_auc),
            "best_cv_score": float(lgb_grid.best_score_)
        }

        mlflow.log_params(best_params)

        mlflow.log_param("target", cat)

        mlflow.log_metrics(metrics)

        mlflow.set_tags({
            "model_type": "LightGBM",
            "target": cat
        })

        signature = infer_signature(X_test, proba)

        registered_model_name = f"lightgbm_{cat}"

        model_info = mlflow.lightgbm.log_model(
            lgb_model=lgb_best,
            artifact_path="model",
            signature=signature,
            input_example=X_test.head(5),
            registered_model_name=registered_model_name,
        )

        new_version = model_info.registered_model_version

        client.set_registered_model_alias(
            registered_model_name,
            "prd",
            new_version
        )

        importance_df = pd.DataFrame({
            "feature": X_train.columns,
            "importance": lgb_best.feature_importances_
        }).sort_values("importance", ascending=False)

        importance_path = f"lgbm_feature_importance_{cat}.csv"

        importance_df.to_csv(
            importance_path,
            index=False
        )

        mlflow.log_artifact(importance_path)

        results.append({
            "category": cat,
            "roc_auc_test": roc_auc,
            "best_cv_score": lgb_grid.best_score_,
            "best_params": best_params,
            "run_id": mlflow.active_run().info.run_id,
            "model_version": new_version
        })

        print("ROC-AUC TEST:", roc_auc)
        print("Best CV Score:", lgb_grid.best_score_)
        print("Best Params:", best_params)

results_lgbm = pd.DataFrame(results)

print(results_lgbm)

TARGET: acute_toxicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012136 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020218 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010938 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.014664 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007862 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008023 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004726 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014875 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   4.7s
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005739 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.1s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.021487 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.1s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002103 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.7s
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.079873 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.1s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.2s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.071058 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.039254 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  10.8s
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004502 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  11.2s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002965 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=   9.2s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.070315 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  10.4s
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=   9.4s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.023509 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  10.9s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.053601 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.045268 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  10.4s
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  11.0s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.017790 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.025155 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  10.5s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005558 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  10.3s
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.057992 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=   9.3s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.054603 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  10.3s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.028264 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.2s
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008102 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   4.6s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002353 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  17.7s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005268 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  17.9s
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.027605 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.1s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.058224 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12613
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.1s
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.028044 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12618
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302786 -> initscore=-0.834066
[LightGBM] [Info] Start training from score -0.834066
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  20.4s
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=1.0; total time=  20.4s
[LightGBM] [Info] Number of positive: 1238, number of negative: 2854
[LightGBM] [Info] Number of positive: 1239, number of negative: 2853
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.021125 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12474
[LightGBM] [Info] Number of data points in the train set: 4092, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.302542 -> initscore=-0.835224
[LightGBM] [Info] Start training from score -0.835224
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.028784 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12613

2026/05/27 16:08:26 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_acute_toxicity'.
2026/05/27 16:08:27 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_acute_toxicity, version 1
Created version '1' of model 'lightgbm_acute_toxicity'.

ROC-AUC TEST: 0.8608340870264294
Best CV Score: 0.8414241127645447
Best Params: {'learning_rate': 0.05, 'n_estimators': 200, 'num_leaves': 31, 'subsample': 0.8}
🏃 View run lgbm_acute_toxicity at: http://localhost:5050/#/experiments/3/runs/d4300da6389540678b9dbb7931e170ba
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: carcinogenicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 552, number of negative: 363
[LightGBM] [Info] Number of positive: 553, number of negative: 362
[LightGBM] [Info] Number of positive: 553, number of negative: 363
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005372 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8692
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007571 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8623
[LightGBM] [Info] Number of data points in the train set: 915, number of used features: 77
[LightGBM] [Info] Number of data points in the train set: 915, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.604372 -> initscore=0.423714
[LightGBM] [Info] Start training from score 0.423714
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.603279 -> initscore=0.419145
[LightGBM] [Info] Start training from score 0.419145
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008375 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8676
[LightGBM] [Info] Number of data points in the train set: 916, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.603712 -> initscore=0.420955
[LightGBM] [Info] Start training from score 0.420955
[LightGBM] [Info] Number of positive: 552, number of negative: 363
[LightGBM] [Info] Number of positive: 553, number of negative: 362
[LightGBM] [Info] Number of positive: 553, number of negative: 363
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005885 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8623
[LightGBM] [Info] Number of data points in the train set: 915, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.603279 -> initscore=0.419145
[LightGBM] [Info] Start training from score 0.419145
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012237 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8676
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009624 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 8692
[LightGBM] [Info] Number of data points in the train set: 916, number of used features: 78
[LightGBM] [Info] Number of data points in the train set: 915, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.604372 -> initscore=0.423714
[LightGBM] [Info] Start training from score 0.423714
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.603712 -> initscore=0.420955
[LightGBM] [Info] Start training from score 0.420955
[LightGBM] [Info] Number of positive: 552, number of negative: 363
[LightGBM] [Info] Number of positive: 553, number of negative: 362
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002723 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 8692
[LightGBM] [Info] Number of data points in the train set: 915, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.604372 -> initscore=0.423714
[LightGBM] [Info] Start training from score 0.423714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.034934 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 8623
[LightGBM] [Info] Number of data points in the train set: 915, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.603279 -> initscore=0.419145
[LightGBM] [Info] Start training from score 0.419145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

2026/05/27 16:09:13 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_carcinogenicity'.
2026/05/27 16:09:14 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_carcinogenicity, version 1
Created version '1' of model 'lightgbm_carcinogenicity'.

ROC-AUC TEST: 0.7495050904977376
Best CV Score: 0.7104196425137482
Best Params: {'learning_rate': 0.05, 'n_estimators': 200, 'num_leaves': 31, 'subsample': 0.8}
🏃 View run lgbm_carcinogenicity at: http://localhost:5050/#/experiments/3/runs/18f01acfa2f6482d8909f697e54ffd4d
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: cardiotoxicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.039557 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Total Bins 14574
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.033062 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14574
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.088753 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14565
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.122607 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14580
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.120103 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14565

[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.106810 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14574
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.182419 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14565
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.064268 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14580
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=  20.3s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=  20.9s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=  21.0s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=  21.0s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=  21.3s
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.013596 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14580
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.045491 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14574
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.215575 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14580
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.213644 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14565
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.062439 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14565
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=  25.3s
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011847 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14574
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  30.1s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  30.4s
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.102938 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14580
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.054176 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14565
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  26.4s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  27.2s
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.077615 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14574
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.096173 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14580
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  31.0s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  33.4s
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  33.7s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.072536 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14565
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.089698 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14574
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.102896 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14580
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  31.6s
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.062884 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14565
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  31.0s
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.140377 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14574
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  38.4s
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.159512 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14580
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  31.7s
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  31.9s
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.095328 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[LightGBM] [Info] Total Bins 14574
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.057327 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14565
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=  15.6s
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.141756 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14580
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=  20.3s
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  48.5s
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  47.6s
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.119741 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14565
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  48.7s
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.375221 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14574
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.104979 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14580
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068993 -> initscore=-2.602266
[LightGBM] [Info] Start training from score -2.602266
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=1.0; total time=  49.0s
[LightGBM] [Info] Number of positive: 11812, number of negative: 159380
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.149252 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 14565
[LightGBM] [Info] Number of data points in the train set: 171192, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.068999 -> initscore=-2.602175
[LightGBM] [Info] Start training from score -2.602175
[LightGBM] [Info] Number of positive: 11811, number of negative: 159381
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.123762 seconds.
You can set `force_row_wise=true` to remove the overhead.

2026/05/27 16:12:59 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_cardiotoxicity'.
2026/05/27 16:13:00 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_cardiotoxicity, version 1
Created version '1' of model 'lightgbm_cardiotoxicity'.

ROC-AUC TEST: 0.9159840100273763
Best CV Score: 0.9066658725116438
Best Params: {'learning_rate': 0.1, 'n_estimators': 400, 'num_leaves': 63, 'subsample': 0.8}
🏃 View run lgbm_cardiotoxicity at: http://localhost:5050/#/experiments/3/runs/1df3f766b7c14075b3a75f4a5951429f
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: dermal_toxicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 1104, number of negative: 482
[LightGBM] [Info] Number of positive: 1104, number of negative: 483
[LightGBM] [Info] Number of positive: 1104, number of negative: 483
[LightGBM] [Info] Number of positive: 1104, number of negative: 482
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004897 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10966
[LightGBM] [Info] Number of data points in the train set: 1586, number of used features: 78
[LightGBM] [Info] Number of positive: 1104, number of negative: 483
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.696091 -> initscore=0.828751
[LightGBM] [Info] Start training from score 0.828751
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004137 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10826
[LightGBM] [Info] Number of data points in the train set: 1587, number of used features: 78
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004140 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10911
[LightGBM] [Info] Number of data points in the train set: 1587, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.695652 -> initscore=0.826679
[LightGBM] [Info] Start training from score 0.826679
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005482 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.695652 -> initscore=0.826679
[LightGBM] [Info] Start training from score 0.826679
[LightGBM] [Info] Total Bins 10966
[LightGBM] [Info] Number of data points in the train set: 1586, number of used features: 78
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003783 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10911
[LightGBM] [Info] Number of data points in the train set: 1587, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.695652 -> initscore=0.826679
[LightGBM] [Info] Start training from score 0.826679
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.696091 -> initscore=0.828751
[LightGBM] [Info] Start training from score 0.828751
[LightGBM] [Info] Number of positive: 1104, number of negative: 483
[LightGBM] [Info] Number of positive: 1104, number of negative: 482
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005104 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10826
[LightGBM] [Info] Number of data points in the train set: 1587, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.695652 -> initscore=0.826679
[LightGBM] [Info] Start training from score 0.826679
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004178 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10966
[LightGBM] [Info] Number of data points in the train set: 1586, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.696091 -> initscore=0.828751
[LightGBM] [Info] Start training from score 0.828751
[LightGBM] [Info] Number of positive: 1104, number of negative: 483
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004405 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10911
[LightGBM] [Info] Number of data points in the train set: 1587, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.695652 -> initscore=0.826679
[LightGBM] [Info] Start training from score 0.826679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   4.7s
[LightGBM] [Info] Number of positive: 1104, number of negative: 483
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.042830 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10826
[LightGBM] [Info] Number of data points in the train set: 1587, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.695652 -> initscore=0.826679
[LightGBM] [Info] Start training from score 0.826679
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   4.8s
[LightGBM] [Info] Number of positive: 1104, number of negative: 482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022996 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf[LightGBM] [Info] Number of data points in the train set: 1586, number of used features: 78

[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.696091 -> initscore=0.828751
[LightGBM] [Info] Start training from score 0.828751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.5s
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 1104, number of negative: 483
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001727 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10911
[LightGBM] [Info] Number of data points in the train set: 1587, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.695652 -> initscore=0.826679
[LightGBM] [Info] Start training from score 0.826679
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.6s
[LightGBM] [Info] Number of positive: 1104, number of negative: 483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.6s
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007588 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of data points in the train set: 1587, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.695652 -> initscore=0.826679
[LightGBM] [Info] Start training from score 0.826679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 1104, number of negative: 482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.027901 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10966
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.7s
[LightGBM] [Info] Number of data points in the train set: 1586, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.696091 -> initscore=0.828751
[LightGBM] [Info] Start training from score 0.828751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 1104, number of negative: 483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.027689 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10911
[LightGBM] [Info] Number of data points in the train set: 1587, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.695652 -> initscore=0.826679
[LightGBM] [Info] Start training from score 0.826679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

2026/05/27 16:14:26 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_dermal_toxicity'.
2026/05/27 16:14:27 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_dermal_toxicity, version 1
Created version '1' of model 'lightgbm_dermal_toxicity'.

ROC-AUC TEST: 0.8014385993007179
Best CV Score: 0.7940465389797472
Best Params: {'learning_rate': 0.05, 'n_estimators': 200, 'num_leaves': 31, 'subsample': 0.8}
🏃 View run lgbm_dermal_toxicity at: http://localhost:5050/#/experiments/3/runs/e19529be901a4b909e29508bc67652d3
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: genotoxicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[LightGBM] [Info] Number of positive: 2586, number of negative: 4397
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027391 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12832
[LightGBM] [Info] Number of data points in the train set: 6984, number of used features: 78
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.030425 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12832
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.033435 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6984, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370418 -> initscore=-0.530424
[LightGBM] [Info] Start training from score -0.530424
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370418 -> initscore=-0.530424
[LightGBM] [Info] Start training from score -0.530424
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.031996 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.166958 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[LightGBM] [Info] Number of positive: 2586, number of negative: 4397
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006107 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Number of positive: 2586, number of negative: 4397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005300 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003574 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   7.6s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   7.7s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   7.7s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025748 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12832
[LightGBM] [Info] Number of data points in the train set: 6984, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370418 -> initscore=-0.530424
[LightGBM] [Info] Start training from score -0.530424[LightGBM] [Info] Number of positive: 2586, number of negative: 4397

[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   7.9s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.093885 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.024484 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.042422 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12832
[LightGBM] [Info] Number of data points in the train set: 6984, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370418 -> initscore=-0.530424
[LightGBM] [Info] Start training from score -0.530424
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   8.5s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   8.6s
[LightGBM] [Info] Number of positive: 2586, number of negative: 4397
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.029260 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.017311 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  13.6s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.037774 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12832
[LightGBM] [Info] Number of data points in the train set: 6984, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370418 -> initscore=-0.530424
[LightGBM] [Info] Start training from score -0.530424
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  14.7s
[LightGBM] [Info] Number of positive: 2586, number of negative: 4397
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014171 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  11.4s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011969 seconds.
You can set `force_col_wise=true` to remove the overhead.[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  11.3s

[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.131089 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12832
[LightGBM] [Info] Number of data points in the train set: 6984, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370418 -> initscore=-0.530424
[LightGBM] [Info] Start training from score -0.530424
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  11.7s
[LightGBM] [Info] Number of positive: 2586, number of negative: 4397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.018219 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  11.5s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.044600 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  13.5s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.081434 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12832
[LightGBM] [Info] Number of data points in the train set: 6984, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370418 -> initscore=-0.530424
[LightGBM] [Info] Start training from score -0.530424
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  13.3s
[LightGBM] [Info] Number of positive: 2586, number of negative: 4397
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004521 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  11.0s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008455 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  14.2s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007462 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12832
[LightGBM] [Info] Number of data points in the train set: 6984, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370418 -> initscore=-0.530424
[LightGBM] [Info] Start training from score -0.530424
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  12.9s
[LightGBM] [Info] Number of positive: 2586, number of negative: 4397
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013758 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  14.6s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.099662 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.9s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.089727 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12832
[LightGBM] [Info] Number of data points in the train set: 6984, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370418 -> initscore=-0.530424
[LightGBM] [Info] Start training from score -0.530424
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.9s
[LightGBM] [Info] Number of positive: 2586, number of negative: 4397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.042681 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  23.7s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.095704 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  23.9s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.056848 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12832
[LightGBM] [Info] Number of data points in the train set: 6984, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370418 -> initscore=-0.530424
[LightGBM] [Info] Start training from score -0.530424
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.7s
[LightGBM] [Info] Number of positive: 2586, number of negative: 4397
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004681 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12886
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370328 -> initscore=-0.530810
[LightGBM] [Info] Start training from score -0.530810
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.5s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4396
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.047087 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12847
[LightGBM] [Info] Number of data points in the train set: 6983, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370471 -> initscore=-0.530196
[LightGBM] [Info] Start training from score -0.530196
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  27.0s
[LightGBM] [Info] Number of positive: 2587, number of negative: 4397
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008221 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12832

2026/05/27 16:16:03 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_genotoxicity'.
2026/05/27 16:16:06 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_genotoxicity, version 1
Created version '1' of model 'lightgbm_genotoxicity'.

ROC-AUC TEST: 0.9129913161991335
Best CV Score: 0.9054353260487447
Best Params: {'learning_rate': 0.05, 'n_estimators': 400, 'num_leaves': 63, 'subsample': 0.8}
🏃 View run lgbm_genotoxicity at: http://localhost:5050/#/experiments/3/runs/53c5e1042be0473685b1c45ff223c808
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: hepatotoxicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 1004, number of negative: 718
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006494 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007514 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11370
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008776 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11308
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008190 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11370
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002167 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11370
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003741 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] Number of data points in the train set: 1722, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.026189 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583043 -> initscore=0.335278
[LightGBM] [Info] Start training from score 0.335278
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 1004, number of negative: 718
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.045640 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11308
[LightGBM] [Info] Number of data points in the train set: 1722, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583043 -> initscore=0.335278
[LightGBM] [Info] Start training from score 0.335278
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   9.0s
[LightGBM] [Info] Number of positive: 1004, number of negative: 718
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002156 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11308
[LightGBM] [Info] Number of data points in the train set: 1722, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583043 -> initscore=0.335278
[LightGBM] [Info] Start training from score 0.335278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   9.5s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.033675 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   9.8s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   9.9s
[LightGBM] [Info] Number of positive: 1004, number of negative: 718
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002621 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11308
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.077487 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11370
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] Number of data points in the train set: 1722, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583043 -> initscore=0.335278
[LightGBM] [Info] Start training from score 0.335278
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=  10.1s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005813 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=  10.4s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001646 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11370
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  15.8s
[LightGBM] [Info] Number of positive: 1004, number of negative: 718
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003201 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11308
[LightGBM] [Info] Number of data points in the train set: 1722, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583043 -> initscore=0.335278
[LightGBM] [Info] Start training from score 0.335278
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  17.1s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009768 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  13.5s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  13.3s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Number of positive: 1004, number of negative: 718
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.018839 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11370
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.030627 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11308
[LightGBM] [Info] Number of data points in the train set: 1722, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583043 -> initscore=0.335278
[LightGBM] [Info] Start training from score 0.335278
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  13.5s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.024335 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  14.9s
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003227 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11370
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  14.0s
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671[LightGBM] [Info] Number of positive: 1004, number of negative: 718

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.132824 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11308
[LightGBM] [Info] Number of data points in the train set: 1722, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583043 -> initscore=0.335278
[LightGBM] [Info] Start training from score 0.335278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  14.5s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003977 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  13.0s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004477 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11370
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  14.6s
[LightGBM] [Info] Number of positive: 1004, number of negative: 718
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011096 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11308
[LightGBM] [Info] Number of data points in the train set: 1722, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583043 -> initscore=0.335278
[LightGBM] [Info] Start training from score 0.335278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  13.1s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.042063 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  14.9s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.081193 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11370
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.5s
[LightGBM] [Info] Number of positive: 1004, number of negative: 718
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007308 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11308
[LightGBM] [Info] Number of data points in the train set: 1722, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583043 -> initscore=0.335278
[LightGBM] [Info] Start training from score 0.335278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   7.1s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009296 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  25.0s
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.024523 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11370
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  25.1s
[LightGBM] [Info] Number of positive: 1004, number of negative: 718
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=1.0; total time=  24.9s
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  25.4s
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.056407 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11308
[LightGBM] [Info] Number of data points in the train set: 1722, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583043 -> initscore=0.335278
[LightGBM] [Info] Start training from score 0.335278
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Number of positive: 1004, number of negative: 717
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.036723 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11318
[LightGBM] [Info] Number of data points in the train set: 1721, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.583382 -> initscore=0.336671
[LightGBM] [Info] Start training from score 0.336671

2026/05/27 16:17:40 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_hepatotoxicity'.
2026/05/27 16:17:40 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_hepatotoxicity, version 1
Created version '1' of model 'lightgbm_hepatotoxicity'.

ROC-AUC TEST: 0.7881632532318341
Best CV Score: 0.8098707135841461
Best Params: {'learning_rate': 0.1, 'n_estimators': 200, 'num_leaves': 31, 'subsample': 0.8}
🏃 View run lgbm_hepatotoxicity at: http://localhost:5050/#/experiments/3/runs/9220e80f59e44d038c1108552138c275
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: ocular_toxicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 2459, number of negative: 491
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008708 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.024190 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11139
[LightGBM] [Info] Total Bins 11136
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] Number of data points in the train set: 2950, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833503 -> initscore=1.610659
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833559 -> initscore=1.611066
[LightGBM] [Info] Start training from score 1.611066
[LightGBM] [Info] Number of positive: 2459, number of negative: 491
[LightGBM] [Info] Start training from score 1.610659
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.024168 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11148
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833842 -> initscore=1.613105
[LightGBM] [Info] Start training from score 1.613105
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.040463 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11136
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833503 -> initscore=1.610659
[LightGBM] [Info] Start training from score 1.610659
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.074267 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11148
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833842 -> initscore=1.613105
[LightGBM] [Info] Start training from score 1.613105
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.066683 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11139
[LightGBM] [Info] Number of data points in the train set: 2950, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833559 -> initscore=1.611066
[LightGBM] [Info] Start training from score 1.611066
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.059781 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11148
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833842 -> initscore=1.613105
[LightGBM] [Info] Start training from score 1.613105
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007408 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11136
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833503 -> initscore=1.610659
[LightGBM] [Info] Start training from score 1.610659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   9.0s
[LightGBM] [Info] Number of positive: 2459, number of negative: 491
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002468 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11139
[LightGBM] [Info] Number of data points in the train set: 2950, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833559 -> initscore=1.611066
[LightGBM] [Info] Start training from score 1.611066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   9.4s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   9.4s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   9.4s
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020028 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11136
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833503 -> initscore=1.610659
[LightGBM] [Info] Start training from score 1.610659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008862 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11148
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833842 -> initscore=1.613105
[LightGBM] [Info] Start training from score 1.613105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   9.6s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   9.6s
[LightGBM] [Info] Number of positive: 2459, number of negative: 491
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003482 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11139
[LightGBM] [Info] Number of data points in the train set: 2950, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833559 -> initscore=1.611066
[LightGBM] [Info] Start training from score 1.611066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019371 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11148
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833842 -> initscore=1.613105
[LightGBM] [Info] Start training from score 1.613105
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006632 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11136
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833503 -> initscore=1.610659
[LightGBM] [Info] Start training from score 1.610659
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  13.8s
[LightGBM] [Info] Number of positive: 2459, number of negative: 491
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003949 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11139
[LightGBM] [Info] Number of data points in the train set: 2950, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833559 -> initscore=1.611066
[LightGBM] [Info] Start training from score 1.611066
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  15.0s
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010360 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11136
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833503 -> initscore=1.610659
[LightGBM] [Info] Start training from score 1.610659
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  11.5s
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.046043 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11148
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833842 -> initscore=1.613105
[LightGBM] [Info] Start training from score 1.613105
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  11.6s
[LightGBM] [Info] Number of positive: 2459, number of negative: 491
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  11.7s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.029227 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11139
[LightGBM] [Info] Number of data points in the train set: 2950, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833559 -> initscore=1.611066
[LightGBM] [Info] Start training from score 1.611066
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005621 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11136
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833503 -> initscore=1.610659
[LightGBM] [Info] Start training from score 1.610659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  12.5s
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.085339 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11148
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833842 -> initscore=1.613105
[LightGBM] [Info] Start training from score 1.613105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  12.8s
[LightGBM] [Info] Number of positive: 2459, number of negative: 491
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004209 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11139
[LightGBM] [Info] Number of data points in the train set: 2950, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833559 -> initscore=1.611066
[LightGBM] [Info] Start training from score 1.611066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  13.4s
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010575 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11136
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833503 -> initscore=1.610659
[LightGBM] [Info] Start training from score 1.610659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  13.5s
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.021188 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11148
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833842 -> initscore=1.613105
[LightGBM] [Info] Start training from score 1.613105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  13.9s
[LightGBM] [Info] Number of positive: 2459, number of negative: 491
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004906 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11139
[LightGBM] [Info] Number of data points in the train set: 2950, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833559 -> initscore=1.611066
[LightGBM] [Info] Start training from score 1.611066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  11.2s
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020522 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11136
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833503 -> initscore=1.610659
[LightGBM] [Info] Start training from score 1.610659
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  11.4s
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.150676 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11148
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833842 -> initscore=1.613105
[LightGBM] [Info] Start training from score 1.613105
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.3s
[LightGBM] [Info] Number of positive: 2459, number of negative: 491
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.021216 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11139
[LightGBM] [Info] Number of data points in the train set: 2950, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833559 -> initscore=1.611066
[LightGBM] [Info] Start training from score 1.611066
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.9s
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.067888 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11136
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833503 -> initscore=1.610659
[LightGBM] [Info] Start training from score 1.610659
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  21.6s
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.050695 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11148
[LightGBM] [Info] Number of data points in the train set: 2949, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833842 -> initscore=1.613105
[LightGBM] [Info] Start training from score 1.613105
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.4s
[LightGBM] [Info] Number of positive: 2459, number of negative: 491
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003216 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11139
[LightGBM] [Info] Number of data points in the train set: 2950, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.833559 -> initscore=1.611066
[LightGBM] [Info] Start training from score 1.611066
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=1.0; total time=  21.5s
[LightGBM] [Info] Number of positive: 2458, number of negative: 491
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.3s
[LightGBM] [Info] Number of positive: 2459, number of negative: 490
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004578 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11148

2026/05/27 16:19:09 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_ocular_toxicity'.
2026/05/27 16:19:09 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_ocular_toxicity, version 1
Created version '1' of model 'lightgbm_ocular_toxicity'.

ROC-AUC TEST: 0.903893259220877
Best CV Score: 0.9188291320285549
Best Params: {'learning_rate': 0.1, 'n_estimators': 200, 'num_leaves': 63, 'subsample': 0.8}
🏃 View run lgbm_ocular_toxicity at: http://localhost:5050/#/experiments/3/runs/77ebf8471ec8450eb193783362fde58d
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: oxidative_stress
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.022130 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.019670 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.015241 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009779 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011377 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019332 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012129 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.017343 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78

[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.4s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.5s
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.036349 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010589 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.7s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027564 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.1s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.068844 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   6.4s
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002852 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.7s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010018 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  11.6s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.082983 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  11.8s
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.066305 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=   9.9s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.031037 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  10.3s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.128813 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  10.4s
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003670 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  10.4s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014339 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  11.4s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003807 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  12.6s
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.050671 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  10.3s
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  10.1s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025263 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.042962 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  10.7s
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.057430 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  10.8s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.018649 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.0s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.018041 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.3s
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007308 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.0s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005846 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.6s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.060452 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=1.0; total time=  20.2s
[LightGBM] [Info] Number of positive: 604, number of negative: 2926
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  23.5s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.025628 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11712
[LightGBM] [Info] Number of data points in the train set: 3530, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171105 -> initscore=-1.577817
[LightGBM] [Info] Start training from score -1.577817
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006622 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11764
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.171340 -> initscore=-1.576163
[LightGBM] [Info] Start training from score -1.576163
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  24.5s
[LightGBM] [Info] Number of positive: 605, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004508 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11711
[LightGBM] [Info] Number of data points in the train set: 3531, number of used features: 78

2026/05/27 16:20:33 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_oxidative_stress'.
2026/05/27 16:20:34 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_oxidative_stress, version 1
Created version '1' of model 'lightgbm_oxidative_stress'.

ROC-AUC TEST: 0.7983206100739302
Best CV Score: 0.7917538878321433
Best Params: {'learning_rate': 0.05, 'n_estimators': 400, 'num_leaves': 63, 'subsample': 0.8}
🏃 View run lgbm_oxidative_stress at: http://localhost:5050/#/experiments/3/runs/2701ae49c8ef44ffb440dfeaf15a2a94
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: respiratory_toxicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 975, number of negative: 276
[LightGBM] [Info] Number of positive: 976, number of negative: 276
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009391 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10259
[LightGBM] [Info] Number of positive: 975, number of negative: 276
[LightGBM] [Info] Number of positive: 975, number of negative: 276
[LightGBM] [Info] Number of data points in the train set: 1251, number of used features: 78
[LightGBM] [Info] Number of positive: 976, number of negative: 276
[LightGBM] [Info] Number of positive: 975, number of negative: 276
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.779376 -> initscore=1.262037
[LightGBM] [Info] Start training from score 1.262037
[LightGBM] [Info] Number of positive: 975, number of negative: 276
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005623 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10276
[LightGBM] [Info] Number of data points in the train set: 1252, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.779553 -> initscore=1.263062
[LightGBM] [Info] Start training from score 1.263062
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005740 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10259
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004558 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10276
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004587 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004656 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10392
[LightGBM] [Info] Total Bins 10392
[LightGBM] [Info] Number of data points in the train set: 1251, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.779376 -> initscore=1.262037
[LightGBM] [Info] Start training from score 1.262037
[LightGBM] [Info] Number of data points in the train set: 1251, number of used features: 78
[LightGBM] [Info] Number of data points in the train set: 1252, number of used features: 78
[LightGBM] [Info] Number of data points in the train set: 1251, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.779376 -> initscore=1.262037
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.779376 -> initscore=1.262037
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.779553 -> initscore=1.263062
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011485 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Start training from score 1.262037
[LightGBM] [Info] Start training from score 1.262037
[LightGBM] [Info] Start training from score 1.263062
[LightGBM] [Info] Total Bins 10259
[LightGBM] [Info] Number of data points in the train set: 1251, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.779376 -> initscore=1.262037
[LightGBM] [Info] Start training from score 1.262037
[LightGBM] [Info] Number of positive: 975, number of negative: 276
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004996 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10392
[LightGBM] [Info] Number of data points in the train set: 1251, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.779376 -> initscore=1.262037
[LightGBM] [Info] Start training from score 1.262037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

2026/05/27 16:21:38 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_respiratory_toxicity'.
2026/05/27 16:21:39 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_respiratory_toxicity, version 1
Created version '1' of model 'lightgbm_respiratory_toxicity'.

ROC-AUC TEST: 0.8877416981925179
Best CV Score: 0.8467619804145122
Best Params: {'learning_rate': 0.05, 'n_estimators': 400, 'num_leaves': 63, 'subsample': 0.8}
🏃 View run lgbm_respiratory_toxicity at: http://localhost:5050/#/experiments/3/runs/b4383cf886384e6fa542c5f051ee5301
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: neuro_sensory_toxicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 890, number of negative: 155
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004019 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10039
[LightGBM] [Info] Number of data points in the train set: 1045, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.851675 -> initscore=1.747796
[LightGBM] [Info] Start training from score 1.747796
[LightGBM] [Info] Number of positive: 890, number of negative: 155
[LightGBM] [Info] Number of positive: 890, number of negative: 156
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004776 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10031
[LightGBM] [Info] Number of data points in the train set: 1045, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.851675 -> initscore=1.747796
[LightGBM] [Info] Number of positive: 890, number of negative: 155
[LightGBM] [Info] Start training from score 1.747796
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006712 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10095
[LightGBM] [Info] Number of positive: 890, number of negative: 155
[LightGBM] [Info] Number of data points in the train set: 1046, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.850860 -> initscore=1.741365
[LightGBM] [Info] Start training from score 1.741365
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003123 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10039
[LightGBM] [Info] Number of data points in the train set: 1045, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.851675 -> initscore=1.747796
[LightGBM] [Info] Start training from score 1.747796
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005916 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10031
[LightGBM] [Info] Number of data points in the train set: 1045, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.851675 -> initscore=1.747796
[LightGBM] [Info] Start training from score 1.747796
[LightGBM] [Info] Number of positive: 890, number of negative: 156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 890, number of negative: 155
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007399 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10095
[LightGBM] [Info] Number of data points in the train set: 1046, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.850860 -> initscore=1.741365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Start training from score 1.741365
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009548 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10039
[LightGBM] [Info] Number of data points in the train set: 1045, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.851675 -> initscore=1.747796
[LightGBM] [Info] Start training from score 1.747796
[LightGBM] [Info] Number of positive: 890, number of negative: 155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006944 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10031
[LightGBM] [Info] Number of data points in the train set: 1045, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.851675 -> initscore=1.747796
[LightGBM] [Info] Start training from score 1.747796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

2026/05/27 16:22:39 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_neuro_sensory_toxicity'.
2026/05/27 16:22:39 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_neuro_sensory_toxicity, version 1
Created version '1' of model 'lightgbm_neuro_sensory_toxicity'.

ROC-AUC TEST: 0.8371561960824113
Best CV Score: 0.8508949228050352
Best Params: {'learning_rate': 0.05, 'n_estimators': 200, 'num_leaves': 31, 'subsample': 0.8}
🏃 View run lgbm_neuro_sensory_toxicity at: http://localhost:5050/#/experiments/3/runs/b2e7ea32377f4831b3fdcaeb8183ea21
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: immuno_hematotoxicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020383 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.035856 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Start training from score -0.660615
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006639 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020089 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12350
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025317 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.030784 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12350
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340852 -> initscore=-0.659499
[LightGBM] [Info] Start training from score -0.659499
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340852 -> initscore=-0.659499
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.659499
[LightGBM] [Info] Start training from score -0.660615
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.052633 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.140222 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.9s
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   6.0s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   6.0s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.017239 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12350
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340852 -> initscore=-0.659499
[LightGBM] [Info] Start training from score -0.659499
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.018123 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.073082 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   6.2s
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.049151 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12350
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340852 -> initscore=-0.659499
[LightGBM] [Info] Start training from score -0.659499
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.9s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   7.0s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.098683 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.083754 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  11.5s
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.181225 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12350
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340852 -> initscore=-0.659499
[LightGBM] [Info] Start training from score -0.659499
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  13.4s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003069 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  11.6s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008646 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  11.6s
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  11.6s
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003598 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12350
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340852 -> initscore=-0.659499
[LightGBM] [Info] Start training from score -0.659499
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.043629 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  11.7s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.060031 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  13.0s
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.080707 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12350
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340852 -> initscore=-0.659499
[LightGBM] [Info] Start training from score -0.659499
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  13.2s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010506 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  11.2s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.045969 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  12.9s
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.096130 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12350
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340852 -> initscore=-0.659499
[LightGBM] [Info] Start training from score -0.659499
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  11.1s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.070662 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  13.0s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003071 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.2s
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.021577 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12350
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340852 -> initscore=-0.659499
[LightGBM] [Info] Start training from score -0.659499
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.3s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.060072 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  21.6s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.147111 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.7s
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  21.6s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.028357 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12350
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340852 -> initscore=-0.659499
[LightGBM] [Info] Start training from score -0.659499
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.127773 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12411
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=1.0; total time=  22.2s
[LightGBM] [Info] Number of positive: 1359, number of negative: 2631
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.033547 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12439
[LightGBM] [Info] Number of data points in the train set: 3990, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.340602 -> initscore=-0.660615
[LightGBM] [Info] Start training from score -0.660615
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.8s
[LightGBM] [Info] Number of positive: 1360, number of negative: 2630

2026/05/27 16:24:03 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_immuno_hematotoxicity'.
2026/05/27 16:24:04 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_immuno_hematotoxicity, version 1
Created version '1' of model 'lightgbm_immuno_hematotoxicity'.

ROC-AUC TEST: 0.8056807120011125
Best CV Score: 0.7983594732503502
Best Params: {'learning_rate': 0.05, 'n_estimators': 200, 'num_leaves': 31, 'subsample': 0.8}
🏃 View run lgbm_immuno_hematotoxicity at: http://localhost:5050/#/experiments/3/runs/837071b44c344b318637914ee93bfcc4
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: reprod_dev_toxicity
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 543, number of negative: 22
[LightGBM] [Info] Number of positive: 543, number of negative: 22
[LightGBM] [Info] Number of positive: 544, number of negative: 22
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.013918 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 6020
[LightGBM] [Info] Number of data points in the train set: 565, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.961062 -> initscore=3.206067
[LightGBM] [Info] Start training from score 3.206067
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012509 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5970
[LightGBM] [Info] Number of data points in the train set: 565, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.961062 -> initscore=3.206067
[LightGBM] [Info] Start training from score 3.206067
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007298 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6113
[LightGBM] [Info] Number of data points in the train set: 566, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.961131 -> initscore=3.207907
[LightGBM] [Info] Start training from score 3.207907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 543, number of negative: 22
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011031 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5970
[LightGBM] [Info] Number of data points in the train set: 565, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.961062 -> initscore=3.206067
[LightGBM] [Info] Start training from score 3.206067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 543, number of negative: 22
[LightGBM] [Info] Number of positive: 544, number of negative: 22
[LightGBM] [Info] Number of positive: 543, number of negative: 22
[LightGBM] [Info] Number of positive: 543, number of negative: 22
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002182 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6020
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002388 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Number of data points in the train set: 565, number of used features: 77
[LightGBM] [Info] Total Bins 5970
[LightGBM] [Info] Number of data points in the train set: 565, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.961062 -> initscore=3.206067
[LightGBM] [Info] Start training from score 3.206067
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.961062 -> initscore=3.206067
[LightGBM] [Info] Start training from score 3.206067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005765 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6113
[LightGBM] [Info] Number of data points in the train set: 566, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.961131 -> initscore=3.207907
[LightGBM] [Info] Start training from score 3.207907
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012478 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 6020
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of data points in the train set: 565, number of used features: 77
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.961062 -> initscore=3.206067
[LightGBM] [Info] Start training from score 3.206067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

2026/05/27 16:24:38 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_reprod_dev_toxicity'.
2026/05/27 16:24:39 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_reprod_dev_toxicity, version 1
Created version '1' of model 'lightgbm_reprod_dev_toxicity'.

ROC-AUC TEST: 0.8290441176470588
Best CV Score: 0.7490844794811585
Best Params: {'learning_rate': 0.05, 'n_estimators': 200, 'num_leaves': 63, 'subsample': 0.8}
🏃 View run lgbm_reprod_dev_toxicity at: http://localhost:5050/#/experiments/3/runs/72be6a7ea7ca4c91981dcace190c20b2
🧪 View experiment at: http://localhost:5050/#/experiments/3

TARGET: endocrine_metabolic_tox
Fitting 3 folds for each of 16 candidates, totalling 48 fits
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020833 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.024330 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016141 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Total Bins 12461
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308601 -> initscore=-0.806667
[LightGBM] [Info] Start training from score -0.806667
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008479 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12461
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308601 -> initscore=-0.806667
[LightGBM] [Info] Start training from score -0.806667
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.052927 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005153 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006349 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012141 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.3s
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   6.4s
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   6.5s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.048967 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12461
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308601 -> initscore=-0.806667
[LightGBM] [Info] Start training from score -0.806667
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004762 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.038295 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   7.1s
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=0.8; total time=   7.2s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010793 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12461
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308601 -> initscore=-0.806667
[LightGBM] [Info] Start training from score -0.806667
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.023465 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=31, subsample=1.0; total time=   7.3s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005398 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  11.8s
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.116375 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12461
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308601 -> initscore=-0.806667
[LightGBM] [Info] Start training from score -0.806667
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  13.6s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.055517 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=0.8; total time=  11.3s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  10.6s
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.076625 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019647 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12461
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308601 -> initscore=-0.806667
[LightGBM] [Info] Start training from score -0.806667
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  12.9s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.056754 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.05, n_estimators=200, num_leaves=63, subsample=1.0; total time=  13.0s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.081879 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  12.5s
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  12.7s
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.030400 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12461
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308601 -> initscore=-0.806667
[LightGBM] [Info] Start training from score -0.806667
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012956 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=0.8; total time=  12.5s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  10.8s
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.093366 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003901 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12461
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308601 -> initscore=-0.806667
[LightGBM] [Info] Start training from score -0.806667
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  10.9s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.079015 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=31, subsample=1.0; total time=  11.1s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.081829 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.2s
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.038039 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12461
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308601 -> initscore=-0.806667
[LightGBM] [Info] Start training from score -0.806667
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   5.4s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.043203 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=1.0; total time=   5.4s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.040700 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.1, n_estimators=200, num_leaves=31, subsample=0.8; total time=   6.0s
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.034891 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12461
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308601 -> initscore=-0.806667
[LightGBM] [Info] Start training from score -0.806667
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  20.6s
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  20.4s
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.049352 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12497
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.049100 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12469
[LightGBM] [Info] Number of data points in the train set: 4232, number of used features: 78
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.308365 -> initscore=-0.807775
[LightGBM] [Info] Start training from score -0.807775
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=1.0; total time=  20.3s
[CV] END learning_rate=0.05, n_estimators=400, num_leaves=63, subsample=0.8; total time=  20.4s
[LightGBM] [Info] Number of positive: 1306, number of negative: 2926
[LightGBM] [Info] Number of positive: 1305, number of negative: 2927
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.052469 seconds.

2026/05/27 16:26:02 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'lightgbm_endocrine_metabolic_tox'.
2026/05/27 16:26:03 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lightgbm_endocrine_metabolic_tox, version 1
Created version '1' of model 'lightgbm_endocrine_metabolic_tox'.

ROC-AUC TEST: 0.7620700239986605
Best CV Score: 0.7504165074793366
Best Params: {'learning_rate': 0.05, 'n_estimators': 200, 'num_leaves': 31, 'subsample': 0.8}
🏃 View run lgbm_endocrine_metabolic_tox at: http://localhost:5050/#/experiments/3/runs/06671b9fb0b6476d952d62e4c1401faa
🧪 View experiment at: http://localhost:5050/#/experiments/3
                   category  roc_auc_test  best_cv_score  \
0            acute_toxicity      0.860834       0.841424
1           carcinogenicity      0.749505       0.710420
2            cardiotoxicity      0.915984       0.906666
3           dermal_toxicity      0.801439       0.794047
4              genotoxicity      0.912991       0.905435
5            hepatotoxicity      0.788163       0.809871
6           ocular_toxicity      0.903893       0.918829
7          oxidative_stress      0.798321       0.791754
8      respiratory_toxicity      0.887742       0.846762
9    neuro_sensory_toxicity      0.837156       0.850895
10    immuno_hematotoxicity      0.805681       0.798359
11      reprod_dev_toxicity      0.829044       0.749084
12  endocrine_metabolic_tox      0.762070       0.750417

                                          best_params  \
0   {'learning_rate': 0.05, 'n_estimators': 200, '...
1   {'learning_rate': 0.05, 'n_estimators': 200, '...
2   {'learning_rate': 0.1, 'n_estimators': 400, 'n...
3   {'learning_rate': 0.05, 'n_estimators': 200, '...
4   {'learning_rate': 0.05, 'n_estimators': 400, '...
5   {'learning_rate': 0.1, 'n_estimators': 200, 'n...
6   {'learning_rate': 0.1, 'n_estimators': 200, 'n...
7   {'learning_rate': 0.05, 'n_estimators': 400, '...
8   {'learning_rate': 0.05, 'n_estimators': 400, '...
9   {'learning_rate': 0.05, 'n_estimators': 200, '...
10  {'learning_rate': 0.05, 'n_estimators': 200, '...
11  {'learning_rate': 0.05, 'n_estimators': 200, '...
12  {'learning_rate': 0.05, 'n_estimators': 200, '...

                              run_id model_version
0   d4300da6389540678b9dbb7931e170ba             1
1   18f01acfa2f6482d8909f697e54ffd4d             1
2   1df3f766b7c14075b3a75f4a5951429f             1
3   e19529be901a4b909e29508bc67652d3             1
4   53c5e1042be0473685b1c45ff223c808             1
5   9220e80f59e44d038c1108552138c275             1
6   77ebf8471ec8450eb193783362fde58d             1
7   2701ae49c8ef44ffb440dfeaf15a2a94             1
8   b4383cf886384e6fa542c5f051ee5301             1
9   b2e7ea32377f4831b3fdcaeb8183ea21             1
10  837071b44c344b318637914ee93bfcc4             1
11  72be6a7ea7ca4c91981dcace190c20b2             1
12  06671b9fb0b6476d952d62e4c1401faa             1

In [11]:
from mlflow.tracking import MlflowClient

experiment_name = "XGB"
artifact_location = "mlflow-artifacts:/"
client = MlflowClient()

exp = mlflow.get_experiment_by_name(experiment_name)
if exp is None:
    exp_id = client.create_experiment(
        name=experiment_name,
        artifact_location=artifact_location
    )
    print("Created experiment:", exp_id)
else:
    exp_id = exp.experiment_id
    print("Using existing experiment:", exp_id, "artifact_location=", exp.artifact_location)

mlflow.set_experiment(experiment_name)

registered_model_name = "XGB_model"

xgb_param_grid = {
    "max_depth": [6, 10],
    "learning_rate": [0.05, 0.1],
    "n_estimators": [200, 400],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

results = []

Created experiment: 4

In [12]:
for cat in y.columns.tolist():

    print(f"\nTARGET: {cat}")

    mask = y[cat].notna()

    X_cat = X[mask]
    y_cat = y.loc[mask, cat]

    if len(y_cat) == 0:
        continue

    if y_cat.nunique() < 2:
        continue

    X_train, X_test, y_train, y_test = train_test_split(
        X_cat,
        y_cat,
        test_size=0.2,
        random_state=42,
        stratify=y_cat
    )

    with mlflow.start_run(run_name=f"xgb_{cat}"):

        xgb_model = xgb.XGBClassifier(
            random_state=42,
            n_jobs=-1,
            eval_metric="logloss",
            tree_method="hist"
        )

        xgb_grid = GridSearchCV(
            estimator=xgb_model,
            param_grid=xgb_param_grid,
            cv=3,
            scoring="roc_auc",
            n_jobs=-1,
            verbose=2
        )

        xgb_grid.fit(X_train, y_train)

        xgb_best = xgb_grid.best_estimator_

        proba = xgb_best.predict_proba(X_test)[:, 1]

        roc_auc = roc_auc_score(y_test, proba)

        best_params = xgb_grid.best_params_

        metrics = {
            "roc_auc_test": float(roc_auc),
            "best_cv_score": float(xgb_grid.best_score_)
        }

        mlflow.log_params(best_params)

        mlflow.log_param("target", cat)

        mlflow.log_metrics(metrics)

        mlflow.set_tags({
            "model_type": "XGBoost",
            "target": cat
        })

        signature = infer_signature(X_test, proba)

        registered_model_name = f"xgboost_{cat}"

        model_info = mlflow.xgboost.log_model(
            xgb_model=xgb_best,
            artifact_path="model",
            signature=signature,
            input_example=X_test.head(5),
            registered_model_name=registered_model_name,
        )

        new_version = model_info.registered_model_version

        client.set_registered_model_alias(
            registered_model_name,
            "prd",
            new_version
        )


        importance_df = pd.DataFrame({
            "feature": X_train.columns,
            "importance": xgb_best.feature_importances_
        }).sort_values("importance", ascending=False)

        importance_path = f"xgb_feature_importance_{cat}.csv"

        importance_df.to_csv(
            importance_path,
            index=False
        )

        mlflow.log_artifact(importance_path)

        results.append({
            "category": cat,
            "roc_auc_test": roc_auc,
            "best_cv_score": xgb_grid.best_score_,
            "best_params": best_params,
            "run_id": mlflow.active_run().info.run_id,
            "model_version": new_version
        })

        print("ROC-AUC TEST:", roc_auc)
        print("Best CV Score:", xgb_grid.best_score_)
        print("Best Params:", best_params)

results_xgb = pd.DataFrame(results)

print(results_xgb)

TARGET: acute_toxicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   6.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   6.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   7.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   7.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   7.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   5.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   5.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   5.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   6.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.1s

2026/05/27 16:30:23 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_acute_toxicity'.
2026/05/27 16:30:23 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_acute_toxicity, version 1
Created version '1' of model 'xgboost_acute_toxicity'.

ROC-AUC TEST: 0.8601386795296955
Best CV Score: 0.8442705852027673
Best Params: {'colsample_bytree': 1.0, 'learning_rate': 0.05, 'max_depth': 6, 'n_estimators': 200, 'subsample': 0.8}
🏃 View run xgb_acute_toxicity at: http://localhost:5050/#/experiments/4/runs/587a6036454d4c55a4ed9ae7cc28b052
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: carcinogenicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.6s

2026/05/27 16:30:43 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_carcinogenicity'.
2026/05/27 16:30:44 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_carcinogenicity, version 1
Created version '1' of model 'xgboost_carcinogenicity'.

ROC-AUC TEST: 0.7465002828054298
Best CV Score: 0.7112624412772007
Best Params: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 400, 'subsample': 0.8}
🏃 View run xgb_carcinogenicity at: http://localhost:5050/#/experiments/4/runs/fa86a3f299494593a4fb25aba83beb1a
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: cardiotoxicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=  12.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=  13.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=  13.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=  13.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=  13.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=  14.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=  26.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=  25.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=  31.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=  31.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=  31.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=  33.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=  44.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=  46.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=  57.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=  58.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time= 1.4min
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time= 1.4min
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=  35.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=  38.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time= 3.1min
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time= 1.0min
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time= 3.1min
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time= 3.0min
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time= 3.1min
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=  32.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=  32.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time= 3.0min
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time= 3.0min
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=  49.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=  50.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=  44.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=  39.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=  40.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=  41.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=  50.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=  50.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=  50.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=  50.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=  55.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=  52.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=  28.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=  28.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=  25.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=  24.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time= 1.6min
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time= 1.6min
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time= 1.5min
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time= 1.6min
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=  23.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time= 1.4min
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=  24.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time= 1.4min
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=  41.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=  42.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=  41.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=  39.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=  39.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=  39.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=  57.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=  56.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time= 1.1min
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time= 1.1min
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time= 1.1min
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=  24.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=  24.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=  22.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=  22.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time= 1.9min
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time= 1.8min
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time= 1.6min
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=  21.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time= 1.7min
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=  21.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time= 1.4min
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time= 1.4min
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=  38.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=  40.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=  40.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=  38.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=  38.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=  37.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=  53.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=  53.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=  55.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=  58.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=  56.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=  56.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time= 1.4min
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time= 1.4min
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time= 1.0min
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=  52.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=  51.2s

2026/05/27 16:43:02 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_cardiotoxicity'.
2026/05/27 16:43:05 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_cardiotoxicity, version 1
Created version '1' of model 'xgboost_cardiotoxicity'.

ROC-AUC TEST: 0.9229089834351001
Best CV Score: 0.9137706125526481
Best Params: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'n_estimators': 400, 'subsample': 0.8}
🏃 View run xgb_cardiotoxicity at: http://localhost:5050/#/experiments/4/runs/9a00351896b247d1a2e63e2a2887e791
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: dermal_toxicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.5s

2026/05/27 16:43:44 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_dermal_toxicity'.
2026/05/27 16:43:45 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_dermal_toxicity, version 1
Created version '1' of model 'xgboost_dermal_toxicity'.

ROC-AUC TEST: 0.8000240211386019
Best CV Score: 0.7971749728767179
Best Params: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'n_estimators': 200, 'subsample': 1.0}
🏃 View run xgb_dermal_toxicity at: http://localhost:5050/#/experiments/4/runs/2b003eb68e4d4a6ebcc2c5f2cc91f7ca
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: genotoxicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   5.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   7.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   7.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   7.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   7.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   8.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   8.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  11.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  11.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  11.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=  11.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=  12.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=  12.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   5.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   9.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   9.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   3.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   3.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   3.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   9.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   5.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   5.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   5.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   5.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   5.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   5.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   7.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   8.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   8.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   8.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   8.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   8.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  12.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  13.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   3.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  13.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=  13.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   5.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=  13.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   5.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   5.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=  13.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   5.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   9.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   9.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   7.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   6.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   7.0s

2026/05/27 16:45:10 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_genotoxicity'.
2026/05/27 16:45:10 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_genotoxicity, version 1
Created version '1' of model 'xgboost_genotoxicity'.

ROC-AUC TEST: 0.9166151932130063
Best CV Score: 0.9094316284600548
Best Params: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'n_estimators': 400, 'subsample': 0.8}
🏃 View run xgb_genotoxicity at: http://localhost:5050/#/experiments/4/runs/653d5b330d25498582377a831e1c3c08
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: hepatotoxicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   5.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   5.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   5.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   5.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.7s

2026/05/27 16:45:52 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_hepatotoxicity'.
2026/05/27 16:45:53 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_hepatotoxicity, version 1
Created version '1' of model 'xgboost_hepatotoxicity'.

ROC-AUC TEST: 0.8009229585950518
Best CV Score: 0.8125664529858758
Best Params: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 6, 'n_estimators': 200, 'subsample': 0.8}
🏃 View run xgb_hepatotoxicity at: http://localhost:5050/#/experiments/4/runs/2df0bd65cabe42258c1657ec1023827b
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: ocular_toxicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.3s

2026/05/27 16:46:29 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_ocular_toxicity'.
2026/05/27 16:46:29 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_ocular_toxicity, version 1
Created version '1' of model 'xgboost_ocular_toxicity'.

ROC-AUC TEST: 0.9088039945357766
Best CV Score: 0.9218675736781446
Best Params: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'n_estimators': 200, 'subsample': 1.0}
🏃 View run xgb_ocular_toxicity at: http://localhost:5050/#/experiments/4/runs/9ff1456079554cea82fc70c38f9fb4b2
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: oxidative_stress
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   6.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   6.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   6.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   6.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   6.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   6.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   4.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   6.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   6.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   6.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   6.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   6.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   6.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   3.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   3.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   4.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.6s

2026/05/27 16:47:19 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_oxidative_stress'.
2026/05/27 16:47:19 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_oxidative_stress, version 1
Created version '1' of model 'xgboost_oxidative_stress'.

ROC-AUC TEST: 0.8043442468245394
Best CV Score: 0.8046316532265685
Best Params: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'n_estimators': 200, 'subsample': 0.8}
🏃 View run xgb_oxidative_stress at: http://localhost:5050/#/experiments/4/runs/8c552755461e4076b9d3987f9ff18706
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: respiratory_toxicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   3.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.0s

2026/05/27 16:47:47 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_respiratory_toxicity'.
2026/05/27 16:47:47 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_respiratory_toxicity, version 1
Created version '1' of model 'xgboost_respiratory_toxicity'.

ROC-AUC TEST: 0.8750788146279949
Best CV Score: 0.8543364610627889
Best Params: {'colsample_bytree': 1.0, 'learning_rate': 0.05, 'max_depth': 6, 'n_estimators': 200, 'subsample': 0.8}
🏃 View run xgb_respiratory_toxicity at: http://localhost:5050/#/experiments/4/runs/b22094e21ec64406afad826e2a25f943
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: neuro_sensory_toxicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   1.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   1.1s

2026/05/27 16:48:09 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_neuro_sensory_toxicity'.
2026/05/27 16:48:09 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_neuro_sensory_toxicity, version 1
Created version '1' of model 'xgboost_neuro_sensory_toxicity'.

ROC-AUC TEST: 0.8546128082817416
Best CV Score: 0.854719562584731
Best Params: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'n_estimators': 200, 'subsample': 0.8}
🏃 View run xgb_neuro_sensory_toxicity at: http://localhost:5050/#/experiments/4/runs/faf0c663a73c41a18190d588fc7a468b
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: immuno_hematotoxicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   8.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.9s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   7.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  10.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  10.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  10.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.7s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   3.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   5.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   5.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   7.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   7.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   7.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   5.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   7.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   7.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  10.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  10.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  10.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.9s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   5.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   5.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   5.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.8s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   6.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.8s

2026/05/27 16:49:19 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_immuno_hematotoxicity'.
2026/05/27 16:49:19 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_immuno_hematotoxicity, version 1
Created version '1' of model 'xgboost_immuno_hematotoxicity'.

ROC-AUC TEST: 0.8059032123487693
Best CV Score: 0.8029370304197198
Best Params: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 6, 'n_estimators': 200, 'subsample': 0.8}
🏃 View run xgb_immuno_hematotoxicity at: http://localhost:5050/#/experiments/4/runs/7a5de01358264fe9987434eb9322fc1f
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: reprod_dev_toxicity
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.7s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   0.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   0.4s

2026/05/27 16:49:29 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_reprod_dev_toxicity'.
2026/05/27 16:49:29 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_reprod_dev_toxicity, version 1
Created version '1' of model 'xgboost_reprod_dev_toxicity'.

ROC-AUC TEST: 0.826593137254902
Best CV Score: 0.7959215554722392
Best Params: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'n_estimators': 200, 'subsample': 0.8}
🏃 View run xgb_reprod_dev_toxicity at: http://localhost:5050/#/experiments/4/runs/a6aa94898dd2435889d30500c2b8b689
🧪 View experiment at: http://localhost:5050/#/experiments/4

TARGET: endocrine_metabolic_tox
Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.4s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.2s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   9.6s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  10.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.3s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.1s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   9.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   1.8s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.0s
[CV] END colsample_bytree=0.8, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.0s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   4.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   4.6s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   5.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   3.0s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   7.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   6.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   7.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.1s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.4s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=0.8; total time=   6.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   6.7s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=200, subsample=1.0; total time=   7.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  10.5s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=  10.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=0.8; total time=   2.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.2s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=0.8; total time=   9.8s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=  10.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=200, subsample=1.0; total time=   2.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.3s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.3s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.6s
[CV] END colsample_bytree=1.0, learning_rate=0.05, max_depth=10, n_estimators=400, subsample=1.0; total time=   9.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   3.9s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=0.8; total time=   4.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=6, n_estimators=400, subsample=1.0; total time=   4.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   5.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=0.8; total time=   5.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   5.1s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=200, subsample=1.0; total time=   5.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   7.0s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=0.8; total time=   5.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.5s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.4s
[CV] END colsample_bytree=1.0, learning_rate=0.1, max_depth=10, n_estimators=400, subsample=1.0; total time=   5.5s

2026/05/27 16:50:36 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'xgboost_endocrine_metabolic_tox'.
2026/05/27 16:50:36 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: xgboost_endocrine_metabolic_tox, version 1
Created version '1' of model 'xgboost_endocrine_metabolic_tox'.

ROC-AUC TEST: 0.7632290290774468
Best CV Score: 0.7559168255437104
Best Params: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 6, 'n_estimators': 200, 'subsample': 0.8}
🏃 View run xgb_endocrine_metabolic_tox at: http://localhost:5050/#/experiments/4/runs/5f33333498ee4ba29fb5d576522063d1
🧪 View experiment at: http://localhost:5050/#/experiments/4
                   category  roc_auc_test  best_cv_score  \
0            acute_toxicity      0.860139       0.844271
1           carcinogenicity      0.746500       0.711262
2            cardiotoxicity      0.922909       0.913771
3           dermal_toxicity      0.800024       0.797175
4              genotoxicity      0.916615       0.909432
5            hepatotoxicity      0.800923       0.812566
6           ocular_toxicity      0.908804       0.921868
7          oxidative_stress      0.804344       0.804632
8      respiratory_toxicity      0.875079       0.854336
9    neuro_sensory_toxicity      0.854613       0.854720
10    immuno_hematotoxicity      0.805903       0.802937
11      reprod_dev_toxicity      0.826593       0.795922
12  endocrine_metabolic_tox      0.763229       0.755917

                                          best_params  \
0   {'colsample_bytree': 1.0, 'learning_rate': 0.0...
1   {'colsample_bytree': 1.0, 'learning_rate': 0.1...
2   {'colsample_bytree': 0.8, 'learning_rate': 0.0...
3   {'colsample_bytree': 0.8, 'learning_rate': 0.0...
4   {'colsample_bytree': 0.8, 'learning_rate': 0.0...
5   {'colsample_bytree': 0.8, 'learning_rate': 0.0...
6   {'colsample_bytree': 0.8, 'learning_rate': 0.0...
7   {'colsample_bytree': 0.8, 'learning_rate': 0.0...
8   {'colsample_bytree': 1.0, 'learning_rate': 0.0...
9   {'colsample_bytree': 0.8, 'learning_rate': 0.0...
10  {'colsample_bytree': 0.8, 'learning_rate': 0.0...
11  {'colsample_bytree': 0.8, 'learning_rate': 0.0...
12  {'colsample_bytree': 0.8, 'learning_rate': 0.0...

                              run_id model_version
0   587a6036454d4c55a4ed9ae7cc28b052             1
1   fa86a3f299494593a4fb25aba83beb1a             1
2   9a00351896b247d1a2e63e2a2887e791             1
3   2b003eb68e4d4a6ebcc2c5f2cc91f7ca             1
4   653d5b330d25498582377a831e1c3c08             1
5   2df0bd65cabe42258c1657ec1023827b             1
6   9ff1456079554cea82fc70c38f9fb4b2             1
7   8c552755461e4076b9d3987f9ff18706             1
8   b22094e21ec64406afad826e2a25f943             1
9   faf0c663a73c41a18190d588fc7a468b             1
10  7a5de01358264fe9987434eb9322fc1f             1
11  a6aa94898dd2435889d30500c2b8b689             1
12  5f33333498ee4ba29fb5d576522063d1             1